# Generated by Django 3.1.4 on 2020-12-28 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now=True)),
                ('hora', models.DateTimeField(auto_now=True)),
                ('descricao', models.CharField(max_length=80, unique=True, verbose_name='Modelo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now=True)),
                ('hora', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=80, unique=True)),
                ('diretorio', models.CharField(max_length=150, verbose_name='Diretorio Arquivos')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelo_processo', to='integrador.modelo', verbose_name='Modelo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now=True)),
                ('hora', models.DateTimeField(auto_now=True)),
                ('descricao', models.CharField(max_length=80, unique=True)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelo_processlist', to='integrador.modelo', verbose_name='Modelo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParametrosProcessList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now=True)),
                ('hora', models.DateTimeField(auto_now=True)),
                ('chave', models.CharField(max_length=50)),
                ('valor', models.CharField(max_length=50)),
                ('processlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros_processlist', to='integrador.processlist', verbose_name='Process List')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now=True)),
                ('hora', models.DateTimeField(auto_now=True)),
                ('situacao', models.CharField(choices=[('SUCESSO', 'SUCESSO'), ('ERRO', 'ERRO')], max_length=20, verbose_name='Situação')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelo_historico', to='integrador.processo', verbose_name='Processo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
