# Generated by Django 3.1.4 on 2020-12-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historico',
            name='observacao',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historico',
            name='situacao',
            field=models.CharField(choices=[('ENVIADO', 'ENVIADO'), ('SUCESSO', 'SUCESSO'), ('ERRO', 'ERRO')], max_length=20, verbose_name='Situação'),
        ),
    ]
