# Generated by Django 3.1.4 on 2020-12-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrador', '0002_auto_20201230_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico',
            name='situacao',
            field=models.CharField(choices=[('ENVIADO PARA PROCESSAMENTO', 'ENVIADO PARA PROCESSAMENTO'), ('CARGA REALIZADA COM SUCESSO', 'CARGA REALIZADA COM SUCESSO'), ('ERRO AO RELIZAR A CARGA DO ARQUIVOS', 'ERRO AO RELIZAR A CARGA DO ARQUIVOS')], max_length=40, verbose_name='Situação'),
        ),
    ]
