# Generated by Django 3.1.4 on 2021-01-04 18:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('integrador', '0003_auto_20201230_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Execucao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now=True)),
                ('hora', models.DateTimeField(auto_now=True)),
                ('descricao', models.CharField(max_length=80)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='processlist',
            name='nome_processo_anaplan',
            field=models.CharField(default=django.utils.timezone.now, max_length=80, unique=True, verbose_name='Nome Processo Anaplan'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ParametrosExecucao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now=True)),
                ('hora', models.DateTimeField(auto_now=True)),
                ('arquivo_anaplan', models.CharField(max_length=50)),
                ('arquivo_forno', models.CharField(max_length=50)),
                ('execucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametrosexecucao_execucao', to='integrador.execucao', verbose_name='Execução')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='execucao',
            name='processlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execucao_processlist', to='integrador.processlist', verbose_name='Process List'),
        ),
    ]
