# Generated by Django 3.1.4 on 2021-01-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrador', '0004_auto_20210104_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processlist',
            name='nome_processo_anaplan',
            field=models.CharField(max_length=80, verbose_name='Nome Processo Anaplan'),
        ),
    ]
