# Generated by Django 3.1.4 on 2021-01-04 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrador', '0006_auto_20210104_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivosExecucao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now=True)),
                ('hora', models.DateTimeField(auto_now=True)),
                ('pasta', models.CharField(max_length=100)),
                ('arquivo', models.CharField(max_length=60)),
                ('execucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execucao_arquivoexecucao', to='integrador.execucao', verbose_name='Execucao')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
