# Generated by Django 3.1.4 on 2021-01-04 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrador', '0008_auto_20210104_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='execucao',
            old_name='produtos',
            new_name='processlist',
        ),
    ]
