# Generated by Django 3.1.4 on 2021-01-04 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrador', '0009_auto_20210104_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='processlist',
            name='modelo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='modelo_processlist', to='integrador.modelo', verbose_name='Modelo'),
            preserve_default=False,
        ),
    ]
