# Generated by Django 3.1.4 on 2021-01-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrador', '0010_processlist_modelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='execucao',
            name='pasta_arquivos',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
