# Generated by Django 3.1.4 on 2021-01-07 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrador', '0011_execucao_pasta_arquivos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='execucao',
            options={'verbose_name_plural': 'Execuções'},
        ),
        migrations.AlterModelOptions(
            name='historico',
            options={'verbose_name_plural': 'Log de Carga Arquivos Anaplan'},
        ),
        migrations.AlterModelOptions(
            name='parametrosexecucao',
            options={'verbose_name': 'Parâmetro'},
        ),
        migrations.AlterModelOptions(
            name='parametrosprocesslist',
            options={'verbose_name_plural': 'Parâmetros'},
        ),
        migrations.AlterModelOptions(
            name='processlist',
            options={'verbose_name': 'Processo', 'verbose_name_plural': 'Processos'},
        ),
        migrations.AlterField(
            model_name='execucao',
            name='descricao',
            field=models.CharField(max_length=80, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='execucao',
            name='pasta_arquivos',
            field=models.CharField(max_length=100, verbose_name='Pasta dos Arquivos'),
        ),
        migrations.AlterField(
            model_name='execucao',
            name='processlist',
            field=models.ManyToManyField(to='integrador.ProcessList', verbose_name='Processos'),
        ),
        migrations.AlterField(
            model_name='historico',
            name='processo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modelo_historico', to='integrador.processo', verbose_name='Processo'),
        ),
        migrations.AlterField(
            model_name='processlist',
            name='descricao',
            field=models.CharField(max_length=80, unique=True, verbose_name='Nome'),
        ),
    ]
