# Generated by Django 3.1.4 on 2021-01-07 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrador', '0012_auto_20210107_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='historico',
            name='execucao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='execucao_historico', to='integrador.execucao', verbose_name='Execucao'),
        ),
    ]
